//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorCollectEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErrorCollectModelContainer : DbContext
    {
        public ErrorCollectModelContainer()
            : base("name=ErrorCollectModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Occurance> Occurances { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<ExceptionData> ExceptionDatas { get; set; }
        public virtual DbSet<ExceptionDataEntry> ExceptionDataEntries { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<HelpLink> HelpLinks { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<ExceptionType> ExceptionTypes { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
