//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorCollectEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExceptionLog()
        {
            this.Occurances = new HashSet<Occurance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> HelpLinkId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DataId { get; set; }
        public int ExceptionTypeId { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual HelpLink HelpLink { get; set; }
        public virtual Source Source { get; set; }
        public virtual ExceptionData ExceltionData { get; set; }
        public virtual ExceptionType ExceptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Occurance> Occurances { get; set; }
    }
}
